spring:
  datasource:
    url: jdbc:h2:mem:test
    username: sa
    password: password
    driver-class-name: org.h2.Driver
#    type: com.zaxxer.hikari.HikariDataSource

#    url: jdbc:mysql://localhost:3306/mySqlPersonApi
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    username: root
#    password: root
  jpa:
    show-sql: true
    open-in-view: false
#    hibernate:
#      ddl-auto: update



    properties:
#      hibernate:
#        flush_before_completion: true
#        jdbc:
#          use_savepoints: false



      jakarta:
        persistence:
          sharedCache:
            mode: ENABLE_SELECTIVE




#    properties:
#      hibernate:
#        jdbc:
#          batch_size: 10
#          order_inserts: true

#logging:
#  level:
#    org.apache.catalina.startup.HostConfig: INFO

csv:
  batch:
    size: 10



